LIBNAME = tb3_rospub
EXTRA_OBJ = rospub.o
EXTRA_CFLAGS += -DNDEBUG
include ../../Makefile.inc
# CXXFLAGS += -std=c++11 -O2
CXXFLAGS += -std=c++11
INCLUDES += -I/opt/ros/kinetic/include
LDFLAGS += -ltf -L/opt/ros/kinetic/lib
