LIBNAME = rossub
EXTRA_CFLAGS += -DNDEBUG
include ../../Makefile.inc
CXXFLAGS += -std=c++11 -O2
INCLUDES += -I/opt/ros/kinetic/include -I./ -I/opt/ros/kinetic/include/opencv-3.3.1-dev/
LDFLAGS += -ltf -ltf2_ros -lactionlib -L/opt/ros/kinetic/lib -lroscpp -lpthread -L/usr/lib/x86_64-linux-gnu/ -lboost_signals -lboost_filesystem -lboost_system -lrosconsole -lrosconsole_log4cxx -lrosconsole_backend_interface -lboost_regex -lboost_system -lboost_thread -lboost_chrono -lboost_date_time -lboost_atomic -lroscpp_serialization -lrostime -lxmlrpcpp -lcpp_common
